### ISSUE TITLE
Cervantes 3 

### ISSUE THREAD

**Issue by elmbeech** [bq/cervantes#4]
dear bg, 
as Cervantes 3 is the only device that is still in stock, I wonder if this firmware going to work with Cervantes 3 too?
and if not, is there a plan to make Cervantes 3 firmware open source?
this is for me the major argument for buying an e-reader.
tnx, bue

**Comment by vanbockryck** [comment]
Hello Elmbeech,

I have a Cervantes 3 and I bought it because I wanted an e-reader with [free software](https://en.wikipedia.org/wiki/Free_software).

If I look in the 'About' section of my device I see that the firmware is published under the GPL and a link to this Github site. So I'm pretty sure Cervantes 3 uses the software from this repo.

**Comment by elmbeech** [comment]
Hi Vanbockryck,

Thank you for the input! Then I will order my self one. 
@ bq, your link in the README file (http://www.mibqyyo.com/actualidad/2014/01/08/bq-ereaders-developers-program-2014) does not mention Cervantes 3. This is why I had to ask. 

Thank you for developing free and open source! 
Elmar

**Comment by pavlo97** [comment]
Hi Elmar and Vanbockryck,

Developers program is already available for Cervantes 3 and 4. All the info can be found at https://blog.bq.com/es/bq-ereaders-developers-program/. Sorry for the delay.

Kind regards,

Pablo.
